# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0a56aa474740de0b31f5d4be4dfb823682db62719a27ed4d293d9aa6a443b0fac548d241e5e118aecfae660039848462cd4bdb6bbcb209b4000bca42ebfb9c3

test:
  secret_key_base: 8015e89b013e3777099d2a1d7a424fa1180fe2d044e2667dfa8d99b404b35dd4521a847299ce6ec68944c1040f74452594c007219964fa55dbacb0ee7b4a936f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
